---

- name: util

  hosts: "{{playbook.hosts}}"
  remote_user: "{{playbook.remote_user}}"
  become: "{{playbook.become}}"
  become_user: "{{playbook.become_user}}"
  become_method: "{{playbook.become_method}}"

  vars:
    os_users:
      - name: nathanwinther
        shell: /bin/bash
        files:
          - dest: .ssh/authorized_keys
            mode: "0640"
            content: |
              ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZEL45sO4NFsgU9kRvwgZnxTHnNr3DDeU88UVWn/tfitE5HgnTL9+sydkr29hAWKMX5vj424qF0R9xGtrdllzb5L0moBskbyX9Y4YZWU6rXow1zTqeyBEenxdM3oNiXCyycwi99HooKdVqtgkJttyGXJ/6h0t4R4mJ3dktut3uncFbS0nnwrF8xxMTq+7a2MjPLBuIfTBhRaUtNFCfkf9b362DrUN+ZuOVkDt5ntBW5qKVpSjvot2wFSB/W982lyv7BBbd3JXby56mCZZeoO21TpLtmKTkWnqzAs7wR4oEToy/2iMSF3fIcNuGfT2OArajdDkgIVDY6Gb42CtbV843 nathanwinther@Nathans-MacBook-Air.local
              ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDf8tOxcdkLFiwJqhDfevFjffI44+B2GlFuGJNlUdPNohXc1GUOOSx3dXEjv2YUEHbEmR/yjlE7Z9xAJnNtnS5mICd5WaVuwrxwHyOP5yNKRw91l8WFr8bGRgnoYNxNSbl/PNsKYAauANFfHblS8hVacWpmwUCod+GqyLRKeQM4CzJC0AkxpFBb6HyhPjfMoFp+boq9fiK9/GqOZTyhocR8NS1QWEX3F1Pvw9K7Y0MowJmrR33Z33Ws5uLXNTq/EtzAYRCw4gVhb+2AoujlvZc3Hm2YZ1M7sihzpjtJoESR1m1BktVF8ox/x7PrnFsU+v1jID9ZJ7UZnDXDou5E6Iah nathanwinther@Nathans-Work-MacBook-Air.local
              ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDfScGeWllFnkEKIF3Q9xwp6/HMol0rIU8cJedDiU5UKBGeBGGwI/cG/E4LJOjWc99os00X1rSAFJ822pKBvPiwXo03JN8WAe92WKVi2j03jt9mlSvK4JTPcLR3f/lIoH60xFXIOSDus2X7GfWrPgjypSpE+BmBIZmmhqqLBPyHiWCKrZ891wtD9d/Yy6dsPXP2WF9WnOEziDOFp1ehxZQwjv4Fq1xjpJ0OPZI2jzrZYvvVlHv9MQFaVWKYujvKj+29xXtDjhSs05/ljBz52Juk5kiKMnQvscLT3gzkRoNv0o1Ofl3Y0kVeykg3WZBvdKfUAPg1y16DW/QMDt92CKuV nathanwinther@iOS
              ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAIEAnt9v4w260PYq/PzMG/TdDzVbxtq+HlYYAJ85YiX2Q4P5qhxs9RcjZI1EjNilRGnuq+SIegwPVJ796vPzZ/L+8GGkGMy4RXMKrVO4otJOyj9cFOKeSZmMWxRUWA/fp2a7zZlVUnE1VP6mQXi5L7pSlGeCw/AJQrMaGRLPxgJ9yAs=
          - dest: .ssh/config
            mode: "0640"
            content: |
              #
              # Adverator v2
              #

              Host ops01
                  HostName ec2-52-21-51-13.compute-1.amazonaws.com
                  User nate
                  LocalForward 3307 adverator-us-east-1a.c60dqbwdga1g.us-east-1.rds.amazonaws.com:3306

              Host qa01
                  HostName ec2-52-0-17-63.compute-1.amazonaws.com
                  User nate
                  LocalForward 3307 adverator-us-east-1a.c60dqbwdga1g.us-east-1.rds.amazonaws.com:3306

              #
              # Taunton Digital Ocean
              #

              Host tauntonredirects
                  Hostname 159.203.78.108
                  User root

              #
              # Taunton AWS servers
              #

              Host appserver1
                  Hostname appserver1.vpc.tauntoncloud.com
                  User nwinther

              Host appserver-1c
                  Hostname ec2-52-91-50-30.compute-1.amazonaws.com
                  User nwinther

              Host dapp-1
                  Hostname ec2-54-87-143-51.compute-1.amazonaws.com
                  User nwinther

              Host dapp-php53srv_01
                  Hostname ec2-34-207-72-189.compute-1.amazonaws.com
                  User nwinther

              Host dapp-php53srv_02
                  Hostname ec2-34-201-98-60.compute-1.amazonaws.com
                  User nwinther

              Host finegarden-dev
                  Hostname ec2-54-210-77-87.compute-1.amazonaws.com
                  User nwinther

              Host finegardenapp1
                  Hostname ec2-52-87-165-248.compute-1.amazonaws.com
                  User nwinther

              Host ims-prod
                  Hostname ec2-34-193-234-6.compute-1.amazonaws.com
                  User nwinther
                  LocalForward 6610 wpressmysql.tauntoncloud.com:3306
                  LocalForward 6611 internal-dbprod-1836264.us-east-1.elb.amazonaws.com:3306

              Host ims-test
                  Hostname ec2-52-205-250-29.compute-1.amazonaws.com
                  User nwinther
                  LocalForward 6606 127.0.0.1:3306

              Host lb1-dapp
                  Hostname ec2-52-1-19-92.compute-1.amazonaws.com
                  User nwinther

              Host varnish_cache-1
                  HostName ec2-52-90-195-155.compute-1.amazonaws.com
                  User nwinther

              Host varnish2_cache-2
                  HostName ec2-52-90-9-75.compute-1.amazonaws.com
                  User nwinther

    os_files:
      - dest: /etc/sudoers.d/users
        mode: "0400"
        content: |
          nathanwinther ALL=(ALL) NOPASSWD: ALL

  tasks:
    - name: apt update
      apt: update_cache=yes

    - name: users
      user: name={{item.name}} state=present createhome=yes generate_ssh_key=yes shell={{item.shell}}
      with_items: "{{os_users}}"

    - name: user files
      copy: content={{item.1.content}} dest=/home/{{item.0.name}}/{{item.1.dest}} force=yes owner={{item.0.name}} group={{item.0.name}} mode={{item.1.mode}}
      with_subelements:
        - "{{os_users}}"
        - "files"

    - name: os files
      copy: content={{item.content}} dest={{item.dest}} force=yes mode={{item.mode}}
      with_items: "{{os_files}}"

    - name: git
      apt: name=git state=latest

    - name: mysql-client
      apt: name=mysql-client state=latest

    - name: screen
      apt: name=screen state=latest

    - name: vim
      apt: name=vim state=latest

